name: Node CI

on: 
  push:
    branches: [ pipeline-teste ]
jobs:
  node:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build, and test
      run: |
        npm install --silent
        npm install react-scripts@3.3.1 -g --silent
        npm run build --if-present
        npm start & npx wait-on http://localhost:3000
      env:
        CI: true
        
  docker-push:
    needs: node

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Download target
      uses: actions/download-artifact@v2
      with:
        name: target-files
        path: target

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag economigos/economigos-app:latest

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASSWD }}

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: economigos/economigos-app:latest
