name: Node CI

on: 
  push:
    branches: [ main ]
jobs:
  node:
    name: Test on node ${{ matrix.node_version }} and ${{ matrix.os }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version: ['10']

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node_version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node_version }}
        
    - name: List dir
      run: |
        ls ./public

    - name: npm install, build and test
      run: |
        npm install
        npm run build --if-present
        
    - name: List dir
      run: |
        ls
        pwd
        
  docker-push:
    needs: node

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag economigos/economigos-app:latest

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASSWD }}

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: economigos/economigos-app:latest
